#!/bin/bash

set -e

# Current working directory
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

#######################################################################
# Load environment variables
#######################################################################

for file in ${DIR}/.{env,env.local}; do
  # shellcheck source=./.env
  [ -r "$file" ] && [ -f "$file" ] && source "$file"
done
unset file

if [ -f "$DIR/bin/shell-common" ]; then
  # shellcheck disable=SC1094
  # shellcheck source=./bin/shell-common
  source "$DIR/bin/shell-common"
else
  echo "shell-common - File does not exist."
  exit 1
fi

# symlink
declare -a files

files+=(
  "$DIR/.env::$HOME/.env"
  "$DIR/profile/.zshrc::$HOME/.zshrc"
  "$DIR/profile/.bash_profile::$HOME/.bash_profile"
  "$DIR/profile/.bash_aliases::$HOME/.bash_aliases"
  "$DIR/config/.gitconfig::$HOME/.gitconfig"
  "$DIR/config/.gitignore::$HOME/.gitignore"
)

for index in "${files[@]}"; do
  source_file="${index%%::*}"
  target_file="${index##*::}"

  if [ -L "$target_file" ]; then
    output "$target_file symbolic exists." 'info'
  else
    if [ ! -f "$source_file" ]; then
      error_exit "File $source_file does not exists."
    fi

    if [ -f "$target_file" ]; then
      error_exit "File $target_file is exists."
    fi

    ln -sf "$source_file" "$target_file"
    chmod 700 "$target_file"
    output "File '$source_file' symlink to '$target_file'" 'success'
  fi

  # rm -f "$target_file"
  unset source_file
  unset target_file
done
unset files
