#!/bin/bash

# Run code inspections from the command line

#https://www.jetbrains.com/help/phpstorm/command-line-code-inspector.html#inspection-profiles

# /Users/soprun/Library/Application Support/JetBrains/Toolbox/apps/PhpStorm/ch-0/203.5981.175/PhpStorm.app/Contents/bin
