#!/bin/bash

# shellcheck source=./../../bin/shell-common
source "${SHELL_HOME}/shell-common"

# Generating a new SSH key
# https://docs.github.com/en/github/authenticating-to-github/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent

identity="$1"
name="$(echo "${identity}" | awk '{print tolower($0)}' | tr -d '\n ' | md5 -q)"
file="$HOME/.ssh/$name"

if [ ! "$identity" ]; then
  log_error "Identity empty!"
fi

if [ -f "$file" ]; then
  log_error "File '$name' exists!"
fi

log_success 'Generating a new SSH key'

log_info "id: $identity"
log_info "name: $name"
log_info "file: $file"

# Generate Keypair - Enter and password
ssh-keygen \
  -q \
  -b 4096 \
  -t "rsa" \
  -N "" \
  -C "$identity" \
  -f "$file"

chmod 600 "$file"
chmod 644 "$file.pub"
# ssh -vT git@github.com
