#!/bin/bash

# shellcheck source=./../../bin/shell-common
source "${SHELL_HOME}/shell-common"

for cmd in "$@"; do {
  log_info "Process \"$cmd\" started"
  $cmd &
  pid=$!
  PID_LIST+=" $pid"
}; done

trap 'echo "kill $(PID_LIST)"' SIGINT

log_info "Parallel processes have started"

wait "$PID_LIST"

log_info "All processes have completed"
