#!/bin/sh

git config --global credential.helper osxkeychain


git config --global user.name "Mona Lisa"


# Кэширование ваших учетных данных GitHub в Git
# https://docs.github.com/en/free-pro-team@latest/github/using-git/caching-your-github-credentials-in-git

# Updating credentials from the macOS Keychain
# https://docs.github.com/en/free-pro-team@latest/github/using-git/updating-credentials-from-the-macos-keychain

# Creating a personal access token
# https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/creating-a-personal-access-token

# Updating credentials from the macOS Keychain
# https://docs.github.com/en/free-pro-team@latest/github/using-git/updating-credentials-from-the-macos-keychain
