#!/bin/bash

# Automating your macOS setup with Homebrew and Cask
# https://medium.com/macoclock/automating-your-macos-setup-with-homebrew-and-cask-e2a103b51af1

set -e

# Check for Homebrew to be present, install if it's missing
if test ! "$(which brew)"; then
  echo "Installing homebrew..."
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

# Update homebrew recipes
# brew update

PACKAGES=(
  git
  docker
  docker-compose
  make
  # gnupg
  # pinentry-mac
  openssl
  mkcert
  shellcheck
  composer
  dotenv-linter
  hadolint
)

# echo "Installing packages..."
# brew install "${PACKAGES[@]}"

# echo "Cleaning up..."
# brew cleanup

#echo "Installing cask..."
#CASKS=(
#  iterm2
#  adobe-acrobat-reader
#  skype
#  slack
#  spotify
#  intellij-idea-ce
#  visual-studio-code
#  steam
#  evernote
#  1password
#  macdown
#)

#echo "Installing cask apps..."
#brew cask install ${CASKS[@]}
