#!/usr/bin/env bash

## Install composer plugin
composer global require \
  hirak/prestissimo \
  nunomaduro/phpinsights \
  phpstan/phpstan \
  phpmetrics/phpmetrics \
  --prefer-dist \
  --prefer-stable \
  --no-progress \
  --no-scripts \
  --no-interaction \
  --ignore-platform-reqs \
  --ansi \
  --profile
