#!/bin/sh

set -ex

# Ask for the administrator password upfront
sudo -v

# Открыты всегда все в списке finder'а. Это очень важно.
defaults write com.apple.Finder FXPreferredViewStyle Nlsv

# Set fast key repeat rate
defaults write NSGlobalDomain KeyRepeat -int 0

# Чтобы показать все скрытые файлы и папки, которые начинаются с символа "."
defaults write com.apple.finder AppleShowAllFiles -bool true

# Show filename extensions by default
defaults write NSGlobalDomain AppleShowAllExtensions -bool true

# Отключите умные тире, так как они раздражают при наборе кода
defaults write NSGlobalDomain NSAutomaticDashSubstitutionEnabled -bool false

# Отключить автоматическую замену точки, так как это раздражает при наборе кода
defaults write NSGlobalDomain NSAutomaticPeriodSubstitutionEnabled -bool false

# Отключить умные кавычки, так как они раздражают при вводе кода
defaults write NSGlobalDomain NSAutomaticQuoteSubstitutionEnabled -bool false

# ############################################## ############################
# Энергосбережение #
# ############################################## ############################

# Включить пробуждение крышки
sudo pmset -a lidwake 1

# Автоматический перезапуск при потере питания
sudo pmset -a autorestart 1

# Автоматическая перезагрузка, если компьютер завис
sudo systemsetup -setrestartfreeze on

# Перевести дисплей в спящий режим через 15 минут
sudo pmset -a displaysleep 15

# Отключить спящий режим машины во время зарядки
sudo pmset -c sleep 0

# Установите аппарат в спящий режим на 5 минут от батареи
sudo pmset -b sleep 5

# Установите задержку режима ожидания на 24 часа (по умолчанию 1 час)
sudo pmset -a standbydelay 86400

# Режим гибернации
# 0: отключить гибернацию (ускоряет переход в спящий режим)
# 3: Скопируйте RAM на диск, чтобы состояние системы можно было восстановить в случае
#     сбой питания.
#sudo pmset -a hibernatemode 0

# Удалите файл образа сна для экономии места на диске
#sudo rm /private/var/vm/sleepimage
# Вместо этого создайте файл с нулевым байтом ...
#sudo touch /private/var/vm/sleepimage
# … И убедитесь, что его нельзя переписать
#sudo chflags uchg /private/var/vm/sleepimage

###############################################################################
# Screen                                                                      #
###############################################################################

# Требовать пароль сразу после того, как начнется спящий режим или заставка
defaults write com.apple.screensaver askForPassword -int 1
defaults write com.apple.screensaver askForPasswordDelay -int 0

# Сохраняем скриншоты на рабочий стол
defaults write com.apple.screencapture location -string "${HOME}/Desktop"

# Сохранение скриншотов в формате PNG (другие варианты: BMP, GIF, JPG, PDF, TIFF)
defaults write com.apple.screencapture type -string "png"

# Отключить тень на скриншотах
defaults write com.apple.screencapture disable-shadow -bool true

# Включить рендеринг субпиксельных шрифтов на ЖК-дисплеях других производителей
# Ссылка: https://github.com/kevinSuttle/macOS-Defaults/issues/17#issuecomment-266633501
defaults write NSGlobalDomain AppleFontSmoothing -int 1

###############################################################################
# Finder                                                                      #
###############################################################################

# Finder: allow quitting via ⌘ + Q; doing so will also hide desktop icons
defaults write com.apple.finder QuitMenuItem -bool true

# Finder: disable window animations and Get Info animations
defaults write com.apple.finder DisableAllAnimations -bool true

# Finder: show hidden files by default
defaults write com.apple.finder AppleShowAllFiles -bool true

# Finder: show all filename extensions
defaults write NSGlobalDomain AppleShowAllExtensions -bool true

# Finder: show status bar
defaults write com.apple.finder ShowStatusBar -bool true

# Finder: show path bar
defaults write com.apple.finder ShowPathbar -bool true

# Display full POSIX path as Finder window title
defaults write com.apple.finder _FXShowPosixPathInTitle -bool true

# Keep folders on top when sorting by name
defaults write com.apple.finder _FXSortFoldersFirst -bool true

# Disable the warning when changing a file extension
defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false

# Avoid creating .DS_Store files on network or USB volumes
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true
defaults write com.apple.desktopservices DSDontWriteUSBStores -bool true

# По умолчанию использовать список во всех окнах Finder
# Четырехбуквенные коды для других режимов просмотра: ʻicnv`, `clmv`,` glyv`
defaults write com.apple.finder FXPreferredViewStyle -string "Nlsv"

# Отключить предупреждение перед очисткой корзины
defaults write com.apple.finder WarnOnEmptyTrash -bool false

# Expand the following File Info panes:
# “General”, “Open with”, and “Sharing & Permissions”
defaults write com.apple.finder FXInfoPanesExpanded -dict \
	General -bool true \
	OpenWith -bool true \
	Privileges -bool true

###############################################################################
# Terminal & iTerm 2                                                          #
###############################################################################

# Only use UTF-8 in Terminal.app
defaults write com.apple.terminal StringEncodings -array 4

# Включить безопасный ввод с клавиатуры в Terminal.app
# См .: https://security.stackexchange.com/a/47786/8918
defaults write com.apple.terminal SecureKeyboardEntry -bool true

# Отключить надоедливые отметки линий
defaults write com.apple.Terminal ShowLineMarks -int 0

# Установите тему Solarized Dark для iTerm
# open "${HOME}/init/Solarized Dark.itermcolors"

# Не отображать раздражающую подсказку при выходе из iTerm
# defaults write com.googlecode.iterm2 PromptOnQuit -bool false

###############################################################################
# Activity Monitor                                                            #
###############################################################################

# Show the main window when launching Activity Monitor
defaults write com.apple.ActivityMonitor OpenMainWindow -bool true

# Visualize CPU usage in the Activity Monitor Dock icon
defaults write com.apple.ActivityMonitor IconType -int 5

# Show all processes in Activity Monitor
defaults write com.apple.ActivityMonitor ShowCategory -int 0

# Sort Activity Monitor results by CPU usage
defaults write com.apple.ActivityMonitor SortColumn -string "CPUUsage"
defaults write com.apple.ActivityMonitor SortDirection -int 0

###############################################################################
# Address Book, Dashboard, iCal, TextEdit, and Disk Utility                   #
###############################################################################

# Enable the debug menu in Address Book
defaults write com.apple.addressbook ABShowDebugMenu -bool true

# Enable the debug menu in iCal (pre-10.8)
defaults write com.apple.iCal IncludeDebugMenu -bool true

# Use plain text mode for new TextEdit documents
defaults write com.apple.TextEdit RichText -int 0
# Open and save files as UTF-8 in TextEdit
defaults write com.apple.TextEdit PlainTextEncoding -int 4
defaults write com.apple.TextEdit PlainTextEncodingForWrite -int 4

###############################################################################
# Mac App Store                                                               #
###############################################################################

# Enable the automatic update check
defaults write com.apple.SoftwareUpdate AutomaticCheckEnabled -bool true

# Check for software updates daily, not just once per week
defaults write com.apple.SoftwareUpdate ScheduleFrequency -int 1

# Download newly available updates in background
defaults write com.apple.SoftwareUpdate AutomaticDownload -int 1

# Install System data files & security updates
defaults write com.apple.SoftwareUpdate CriticalUpdateInstall -int 1

# Automatically download apps purchased on other Macs
defaults write com.apple.SoftwareUpdate ConfigDataInstall -int 1

# Turn on app auto-update
defaults write com.apple.commerce AutoUpdate -bool true

###############################################################################
# Kill Finder                                                                 #
###############################################################################

killall Finder
