#!/bin/sh

# shellcheck source=./../common.sh
source "${CWD}/../common.sh"

# Copy the current branch name to the clipboard.

branch=$(git-branch-name)

log_info "Current branch: $branch"

echo "$branch" | tr -d '\n' | tr -d ' ' | pbcopy
