#!/bin/sh

# shellcheck source=./../common.sh
source "${CWD}/../common.sh"

for cmd in "$@"; do {
  log_info "Process \"$cmd\" started"
  $cmd &
  pid=$!
  PID_LIST+=" $pid"
}; done

trap "kill $PID_LIST" SIGINT

log_info "Parallel processes have started"

wait $PID_LIST

log_info "All processes have completed"
