#!/bin/bash

# shellcheck source=./../../bin/shell-common
source "${SHELL_HOME}/shell-common"

name="$1"
value=""
default_value="$(printenv "$1")"

output "name: $name" "debug"
output "default: $default_value" "debug"

printf "env: %s ${COLOR_CYAN}[%s]${COLOR_RESET}: " "$name" "$default_value"
read -r value

value="${value:-$default_value}"

echo "${name}=\"${value}\"" > "$HOME/.env.local"

output "value: $value" "info"
