---
###########################
###########################
## Linter GitHub Actions ##
###########################
###########################
name: Lint Code Base

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#############################
# Start the job on all push #
#############################
#on:
#  push:
#    branches-ignore: [ master ]
#    # Remove the line above to run when pushing to master
#  pull_request:
#    branches: [ master ]

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

#      ################################
#      # Run Linter against code base #
#      ################################
#      - name: Lint Code Base
#        uses: github/super-linter@v3
#        env:
#          VALIDATE_ALL_CODEBASE: true
#          DEFAULT_BRANCH: master
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          # FILTER_REGEX_INCLUDE: .*bin/.* .*profile/.* ./install
#          FILTER_REGEX_EXCLUDE: .*bin-tools/.* .*functions/.* .*iTerm2/.* .*phpstorm/.*

      - name: Run shellcheck with reviewdog
        # You may pin to the exact commit or the version.
        # uses: reviewdog/action-shellcheck@d1633401834d548d262edaf8cd57ca4910bc9282
        uses: reviewdog/action-shellcheck@v1.0.0
        with:
          # GITHUB_TOKEN.
          github_token:
          # Report level for reviewdog [info,warning,error]
          level: # optional, default is error
          # Reporter of reviewdog command [github-pr-check,github-pr-review].
          # Default is github-pr-check.
          # github-pr-review can use Markdown and add a link to rule page in reviewdog reports.

          reporter: # optional, default is github-pr-check
          # Base directory to run shellcheck. Same as `[path]` of `find` command.
          path: # optional, default is .
          # File patterns of target files. Same as `-name [pattern]` of `find` command.
          pattern: # optional, default is *.sh
          # Exclude patterns of target files. Same as `-not -path [exclude]` of `find` command.
          exclude: # optional
