#!/bin/zsh

# Be very strict
set -euo pipefail

SHELL_DEBUG=0
SHELL_BIN="${HOME}/bin"
SHELL_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"

echo "SHELL_DIR: $SHELL_DIR"
echo "SHELL_BIN: $SHELL_BIN"

# Load the shell dotfiles, and then some:
# * ~/.path can be used to extend `$PATH`.
# * ~/.extra can be used for other settings you don’t want to commit.
for file in ~/.{env,env.local,aliases}; do
  # shellcheck source=./.aliases
  [ -r "$file" ] && [ -f "$file" ] && source "$file"
done
unset file

exit 1

for file in $HOME/bin-other/*; do
  # shellcheck source=./.aliases
  [ -r "$file" ] && [ -f "$file" ] && source "$file"
done
unset file

# Add `~/bin` to the `$PATH` so it includes user's private bin
# export PATH="$HOME/bin/*:$PATH"


###
### System dependencies
### log_info 'Check system required dependencies'

declare -a commands=(
  docker
  docker-compose
  git
  make
  gpg
  mkcert
  openssl
  shellcheck
  tree
  dotenv-linter
  hadolint
)

for command in "${commands[@]}"; do
  if ! command -v "$command" >/dev/null 2>/dev/null; then
    log_warn "${command} is not installed."
  fi
done
