#!/bin/sh

###
### logger
###

log_debug() {
  logger -p user.debug -t "$(basename "${0}")" "$@"
  sleep .3
}

log_success() {
  printf "=>$COLOR_GREEN log:$COLOR_RESET %s\n$COLOR_RESET" "$*"
  logger -p user.info -t "$(basename "${0}")" "$@"
  sleep .3
}

log_info() {
  printf "=>$COLOR_BLUE log:$COLOR_RESET %s\n$COLOR_RESET" "$*"
  logger -p user.info -t "$(basename "${0}")" "$@"
  sleep .3
}

log_warn() {
  printf "=>$COLOR_YELLOW log:$COLOR_RESET %s\n$COLOR_RESET" "$*"
  logger -p user.warn -t "$(basename "${0}")" "$@"
}

log_error() {
  printf "=>$COLOR_RED log:$COLOR_RESET %s\n$COLOR_RESET" "$*" >&2
  logger -p user.error -t "$(basename "${0}")" "$@"
  exit 1
}



# see: https://apple.stackexchange.com/questions/256769/how-to-use-logger-command-on-sierra
### Example

#log_debug 'success'
#log_success 'success'
#log_info 'info'
#log_warn 'warn'
#log_error 'error'

