#!/bin/sh

function print_line() {
    local message="$1"
    local levl="$1"
}


alias print_message="message"
alias print_line="message"

printf

# open -a MyProg.app
# opne -a TextEdit.app 






# https://support.apple.com/guide/terminal/execute-commands-and-run-tools-apdb66b5242-0d18-49fc-9c47-a2498b7c91d5/2.10/mac/10.15
# https://www.geeksforgeeks.org/use-of-submodules-in-github/
